version: '3.8'

services:
  dashboard-cuentas:
    image: dashboard-cuentas
    build: .
    container_name: dashboard_financiero
    ports:
      - "8000:80"
    volumes:
      # Montar tu archivo real con el nombre gen√©rico 'datos.csv' para que el dashboard lo detecte siempre
      - ./datos.csv:/usr/share/nginx/html/datos.csv
    restart: unless-stopped
