version: '3.8'

services:
  miclan-capital:
    image: miclan-capital
    build: .
    container_name: miclan_capital
    ports:
      - "8000:80"
    volumes:
      # Montar tu archivo real con el nombre gen√©rico 'datos.csv' para que el dashboard lo detecte siempre
      - ./datos.csv:/usr/share/nginx/html/datos.csv
    restart: unless-stopped
