version: '3.8'

services:
  miclan-capital:
    build: .
    container_name: miclan_capital
    ports:
      - "8000:8000"
    volumes:
      - ./datos.csv:/app/datos.csv
      - ./Compras-online:/app/Compras-online
    restart: unless-stopped
    environment:
      - PORT=8000
