version: '3.8'

services:
  dashboard-cuentas:
    image: dashboard-cuentas
    build: .
    container_name: dashboard_financiero
    ports:
      - "8000:80"
    volumes:
      # Montar el archivo CSV como volumen para permitir actualizaciones de datos en vivo
      # Aseg√∫rate de que el nombre del archivo coincida con el que tienes en local
      - ./Cuentas_casa+elena2015-2025.csv:/usr/share/nginx/html/Cuentas_casa+elena2015-2025.csv
    restart: unless-stopped
